name: panvimdoc
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/panvimdoc.yml
      - README.md
  workflow_dispatch:
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Run panvimdoc
        uses: kdheepak/panvimdoc@v6
        with:
          vimdoc: triforce
          pandoc: README.md
          version: "NVIM >=v0.10.0"
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v7.2.0
        with:
          commit_message: "docs: auto generate docs"
          branch: ${{ github.head_ref }}

# vim: set ts=2 sts=2 sw=2 et ai si sta:
